### ISSUE TITLE
Screenshot source code in text format

### ISSUE THREAD

**Issue by rsanchezsaez** [eppz/iOS.Library.eppz_xCode#2]
Thanks for sharing this, is one of the most aesthetically pleasant Xcode themes I have seen. And it's refreshing seeing some thought put to the colors rationale.

Could you possibly upload the source code example showed in the screenshot as a plaintext to the *design* branch? I'd like to do some fine-tuning, and that piece of source looks like the quickest way of seeing how everything looks.

Thanks!

**Comment by eppz** [comment]
It is already there in eppz!kit (amongst tasty other stuff) https://github.com/eppz/iOS.Library.eppz_kit/blob/68610cd53390e655ac137255c55e280d39836617/eppz!kit!testbed/EPPZColorThemeTestbed.m

**Comment by rsanchezsaez** [comment]
Oh, didn't see it. Thanks!
