### ISSUE TITLE
Alcatraz.io package is broken

### ISSUE THREAD

**Issue by rsanchezsaez** [eppz/iOS.Library.eppz_xCode#3]
I think that the target URL in [Alcatraz](http://alcatraz.io)'s package is broken. It downloads an HTML file, instead of the proper `eppz!.dvtcolortheme`. Other *color themes* downloaded from Alcatraz do work.

**Comment by eppz** [comment]
I did not submitted to Alcatraz, maybe someone did.

**Comment by rsanchezsaez** [comment]
Maybe you can claim the package as the original author and/or have it fixed. It's a great way of discovering new *color themes* for Xcode.

**Comment by eppz** [comment]
Thanks for the spot, gonna look after.

**Comment by eppz** [comment]
There it goes - https://github.com/supermarin/alcatraz-packages/pull/299/files - probably gonna be merged soon. Thanks.

**Comment by eppz** [comment]
Merged! It should be fine now.

**Comment by rsanchezsaez** [comment]
:+1:
